name: Deploy
on: deployment
jobs:

  production:
    if: github.event.deployment.environment == 'production'
    env:
      DEPLOY_ID: ${{ github.event.deployment.id }}
      DEPLOY_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:

      - name: Simulate a deployment
        run: |
          echo "TODO test"
          echo "TODO build"
          echo "TODO deploy"

      - name: Deployment success
        if: success()
        run: |
          curl -X POST -H "Authorization: token ${DEPLOY_TOKEN}" -H "Accept: application/vnd.github.flash-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/${GITHUB_REPOSITORY}/deployments/${DEPLOY_ID}/statuses --data '{"environment": "production", "state": "success"}'

      - name: Deployment failure
        if: failure()
        run: |
          curl -X POST -H "Authorization: token ${DEPLOY_TOKEN}" -H "Accept: application/vnd.github.flash-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/${GITHUB_REPOSITORY}/deployments/${DEPLOY_ID}/statuses --data '{"environment": "production", "state": "failure"}'
