name: Deploy
on: deployment
jobs:

  production:
    if: github.event.deployment.environment == 'production'
    env:
      DEPLOYMENT_ID: ${{ github.event.deployment.id }}
      DEPLOYMENT_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:

      - name: Deployment start
        run: curl -X POST -H "Authorization: token ${DEPLOYMENT_TOKEN}" -H "Accept: application/vnd.github.flash-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/${GITHUB_REPOSITORY}/deployments/${DEPLOYMENT_ID}/statuses --data "{\"environment\": \"production\", \"state\": \"in_progress\"}"

      - name: Simulate a deployment
        run: |
          echo "TODO test"
          echo "TODO build"
          echo "TODO deploy"

      - name: Deployment success
        if: success()
        run: curl -X POST -H "Authorization: token ${DEPLOYMENT_TOKEN}" -H "Accept: application/vnd.github.flash-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/${GITHUB_REPOSITORY}/deployments/${DEPLOYMENT_ID}/statuses --data "{\"environment\": \"production\", \"state\": \"success\"}"

      - name: Deployment failure
        if: failure()
        run: curl -X POST -H "Authorization: token ${DEPLOYMENT_TOKEN}" -H "Accept: application/vnd.github.flash-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/${GITHUB_REPOSITORY}/deployments/${DEPLOYMENT_ID}/statuses --data "{\"environment\": \"production\", \"state\": \"failure\"}"
